apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: deployment-single-volume-snapshot
spec:
  volumeSnapshotClassName: iscsi-csi-ngxstorage-snapshot-class
  source:
    persistentVolumeClaimName: csi-deployment-pvc
