apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-deployment-single-volume-snapshot
spec:
  storageClassName: iscsi-csi-ngxstorage-class
  dataSource:
    name: deployment-single-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
