apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-csi-app
  labels:
    app: my-csi-app
spec:
  serviceName: my-csi-app # Headless service will be automatically created with this name
  replicas: 4
  selector:
    matchLabels:
      app: my-csi-app
  template:
    metadata:
      labels:
        app: my-csi-app
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
      containers:
      - name: my-frontend
        image: busybox
        volumeMounts:
        - mountPath: "/data"
          name: my-ngx-volume-pvc-template
        command: ["sleep", "1000000"]
  volumeClaimTemplates:
  - metadata:
      name: my-ngx-volume-pvc-template #This name will be used as the base for generating individual PVCs
    spec:
      storageClassName: iscsi-csi-ngxstorage-class
      volumeMode: Filesystem
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi # Request 1GB of storage for each PVC
