kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app-raw-block
spec:
  containers:
  - name: my-frontend
    image: busybox
    volumeDevices:
    - devicePath: "/data"
      name: my-ngx-volume
    command: ["sleep", "1000000"]
  volumes:
  - name: my-ngx-volume
    persistentVolumeClaim:
      claimName: csi-pod-pvc-raw-block
