apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "iscsi-csi-ngxstorage-controller"
  labels:
    app: "iscsi-csi-ngxstorage"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "iscsi-csi-ngxstorage"
      component: "controller"
  template:
    metadata:
      labels:
        app: "iscsi-csi-ngxstorage"
        component: "controller"
    spec:
      serviceAccountName: "iscsi-csi-ngxstorage-service-account"
      securityContext: {}
      nodeSelector:
        kubernetes.io/os: "linux"
      containers:
      - name: "csi-snapshot-controller"
        image: "k8s.gcr.io/sig-storage/snapshot-controller:v6.2.1"
        imagePullPolicy: "Always"
        resources: {}
        args:
        - "--v=5"
        - "--leader-election=true"
      - name: "csi-snapshotter"
        image: "k8s.gcr.io/sig-storage/csi-snapshotter:v6.2.1"
        imagePullPolicy: "Always"
        resources: {}
        args:
        - "--csi-address=$(CSI_ENDPOINT)"
        - "--leader-election"
        - "--timeout=300s"
        - "--v=5"
        env:
        - name: "CSI_ENDPOINT"
          value: "/var/lib/csi/sockets/pluginproxy/iscsi-csi-ngxstorage.sock"
        volumeMounts:
        - name: "domain-socket"
          mountPath: "/var/lib/csi/sockets/pluginproxy/"
      - name: "csi-provisioner"
        image: "registry.k8s.io/sig-storage/csi-provisioner:v3.5.0"
        imagePullPolicy: "Always"
        resources: {}
        args:
        - "--csi-address=$(CSI_ENDPOINT)"
        - "--leader-election"
        - "--timeout=300s"
        - "--v=5"
        env:
        - name: "CSI_ENDPOINT"
          value: "/var/lib/csi/sockets/pluginproxy/iscsi-csi-ngxstorage.sock"
        volumeMounts:
        - name: domain-socket
          mountPath: /var/lib/csi/sockets/pluginproxy
      - name: "csi-attacher"
        image: "registry.k8s.io/sig-storage/csi-attacher:v4.3.0"
        imagePullPolicy: "Always"
        resources: {}
        args:
        - "--csi-address=$(CSI_ENDPOINT)"
        - "--leader-election"
        - "--timeout=300s"
        - "--v=5"
        env:
        - name: MY_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CSI_ENDPOINT"
          value: "/var/lib/csi/sockets/pluginproxy/iscsi-csi-ngxstorage.sock"
        volumeMounts:
        - name: "domain-socket"
          mountPath: "/var/lib/csi/sockets/pluginproxy"
      - name: "csi-resizer"
        image: "gcr.io/k8s-staging-sig-storage/csi-resizer:v1.8.0"
        imagePullPolicy: "Always"
        resources: {}
        args:
        - "--csi-address=$(CSI_ENDPOINT)"
        - "--leader-election"
        - "--timeout=300s"
        - "--v=5"
        env:
        - name: "CSI_ENDPOINT"
          value: "/var/lib/csi/sockets/pluginproxy/iscsi-csi-ngxstorage.sock"
        volumeMounts:
        - name: domain-socket
          mountPath: /var/lib/csi/sockets/pluginproxy/
      - name: "iscsi-csi-ngxstorage-controller"
        securityContext:
          capabilities:
            add: ["NET_RAW"]
        image: "ngxstorage/iscsi-csi-ngxstorage:latest"
        imagePullPolicy: "Always"
        resources: {}
        args:
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--login=$(STORAGE_USERNAMES):$(STORAGE_PASSWORDS)"
        - "--ip=$(STORAGE_IPS)"
        - "--pool-name=$(STORAGE_POOLNAME)"
        - "--portal-group=$(STORAGE_PORTALGRP)"
        - "--nodeid=$(KUBE_NODE_NAME)"
        - "--log=1"
        env:
        - name: "CSI_ENDPOINT"
          value: "unix:///var/lib/csi/sockets/pluginproxy/iscsi-csi-ngxstorage.sock"
        - name: "STORAGE_USERNAMES"
          valueFrom:
            secretKeyRef:
              name: ngxstorage-secret
              key: usernames
        - name: "STORAGE_PASSWORDS"
          valueFrom:
            secretKeyRef:
              name: ngxstorage-secret
              key: passwords
        - name: "STORAGE_IPS"
          valueFrom:
            secretKeyRef:
              name: ngxstorage-secret
              key: ips
        - name: "STORAGE_POOLNAME"
          valueFrom:
            secretKeyRef:
              name: ngxstorage-secret
              key: poolName
        - name: "STORAGE_PORTALGRP"
          valueFrom:
            secretKeyRef:
              name: ngxstorage-secret
              key: portalGroupName
        - name: "KUBE_NODE_NAME"
          value: "controller"
        volumeMounts:
        - name: "domain-socket"
          mountPath: "/var/lib/csi/sockets/pluginproxy"
        - name: "log"
          mountPath: "/host/etc"
          mountPropagation: "HostToContainer"
      volumes:
      - name: "domain-socket"
        emptyDir: {}
      - name: "log"
        hostPath:
          path: "/etc"
          type: "Directory"
