kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: "worker"
  containers:
  - name: my-frontend
    image: busybox
    volumeMounts:
    - mountPath: "/data"
      name: my-ngx-volume
    command: ["sleep", "1000000"]
  volumes:
  - name: my-ngx-volume
    persistentVolumeClaim:
      claimName: csi-pod-pvc
